version: '3.8'
services:
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - NESSIE_CATALOG_DEFAULT_WAREHOUSE=minio
    restart: unless-stopped

  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    ports:
      - "9047:9047"   # Web UI
      - "31010:31010" # Client port
      - "32010:32010" # Arrow Flight
    depends_on:
      - nessie
      - minio
    volumes:
      - dremio_data:/opt/dremio/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=ali
      - MINIO_ROOT_PASSWORD=aliali123
    command: server /data --console-address ":9001"
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=disaster
    restart: unless-stopped

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=disaster
    restart: unless-stopped

volumes:
  minio_data:
  postgres_data:
  mongodb_data:
  cassandra_data:
  dremio_data: