INGESTION:
  DATASETS: [
    "mexwell/significant-volcanic-eruption-database",
    "harshalhonde/tsunami-events-dataset-1900-present",
    "kazushiadachi/global-landslide-data",
    "jacopoferretti/big-eartquakes-1900-1999-dataset",
    "joebeachcapital/earthquakes",
    "brsdincer/wildfire-detection-image-data",
    "sudhanshu432/algerian-forest-fires-cleaned-dataset"]
  BUCKET: lake
  BRONZE: bronze/